name: participants

on:
  schedule: [{ cron: "0 12 * * *" }]  # Roda todo dia ao meio-dia
  workflow_dispatch:                 # Permite executar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICA_TOKEN }}
          filename: metrics.svg
          base: repositories
          plugin_issues: yes
          plugin_issues_assignees: yes
